# Constants
WIDTH = 800
HEIGHT = 600
ALIEN_ANIMATION_DELAY = 50
ALIEN_DROP_SPEED = 10
ALIEN_MOVE_SPEED = 2
ALIEN_SHOOT_CHANCE = 0.01
PLAYER_SPEED = 15
BULLET_SPEED = 10
MISSILE_SPEED = 10
POINTS_PER_ALIEN = 10
FONT_SIZE = 80
COLOR = "white"
ALIEN_WIDTH = 40
ALIEN_HEIGHT = 20
BLOCK_WIDTH = 500  # Width of the block
BLOCK_HEIGHT = 50  # Height of the block
BLOCK_TEXT = "Example"  # Text to display above the player
